---
all:
  children:
    controller:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    owasp_targets:
      hosts:
        rhel9-lab:
          ansible_host: 192.0.2.10
          ansible_user: ansible
          owasp_oscap_datastream: /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
          owasp_oscap_profile: xccdf_org.ssgproject.content_profile_cis_server_l1
          owasp_oscap_report_path: /var/tmp/owasp-oscap-report.html
          owasp_oscap_results_path: /var/tmp/owasp-oscap-results.xml
