---
galaxy_info:
  author: Nuno Martins
  description: OWASP A09 auditd and rsyslog
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
        - "10"
  galaxy_tags:
    - owasp
    - logging
    - audit
dependencies: []
